# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('skills', models.CharField(max_length=200)),
                ('years_of_experience', models.CharField(max_length=60)),
                ('job_type', models.CharField(choices=[('FP', 'FixedPrice'), ('FT', 'Fulltime'), ('PT', 'Parttime'), ('HR', 'Hourly')], max_length=20)),
                ('duration', models.CharField(max_length=60)),
                ('salary', models.CharField(max_length=60)),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(max_length=20000, upload_to='static/resume')),
                ('video', models.FileField(upload_to='static/video')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='WDJob.JobCategory'),
        ),
    ]
